openapi: 3.0.1
info:
  title: REST-API приложения Картотека
  version: 1.0.0
tags:
  - name: test
    description: test
  - name: book
    description: API работы с книгами
  - name: author
    description: API работы с авторами

servers:
  - url: /api/rest

paths:
  /test/test:
    $ref: "./paths/testTest.yaml"

  /book/{id}:
    $ref: "./paths/book/getBookById.yaml"
  /book/list:
    $ref: "./paths/book/findAll.yaml"
  /book/save:
    $ref: "./paths/book/saveBook.yaml"
  /book/delete:
    $ref: "./paths/book/deleteBook.yaml"
  /book/list/search:
    $ref: "./paths/book/findBooksBySearch.yaml"

  /author/{id}:
    $ref: "./paths/author/getById.yaml"
  /author/list:
    $ref: "./paths/author/findAll.yaml"
  /author/save:
    $ref: "./paths/author/saveAuthor.yaml"
  /author/delete:
    $ref: "./paths/author/deleteAuthor.yaml"


